name: SP500 Signal Trading

on:
  schedule:
    - cron: '30 15 * * 1-5'  # Montag bis Freitag um 15:30 UTC (10:30 EST / 16:30 MEZ)
  workflow_dispatch:  # Ermöglicht manuelles Auslösen

jobs:
  trading-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Python einrichten
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Abhängigkeiten installieren
        run: pip install pandas numpy requests ib_insync smtplib

      - name: SP500 Signal generieren
        run: python sp500_data.py

      - name: Trading-Skript ausführen (Käufe/Verkäufe)
        run: python trade_upro.py

      - name: Falls keine Transaktion stattfand, sende eine E-Mail
        if: failure()
        run: python send_alert_email.py

      - name: Logs speichern (optional)
        if: always()
        run: cat trade_log.csv || echo "Keine Log-Datei vorhanden."
