name: IBKR Client Portal API Access

on:
  workflow_dispatch:

jobs:
  fetch-account:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Start Client Portal Gateway
        run: |
          docker run -d --name ibkr-gateway -p 5000:5000 dradrian/ibportal:latest
          echo 'Warte 30 Sekunden...'
          sleep 30

      - name: Login to Gateway
        run: |
          curl -k -s -c cookies.txt -X POST https://localhost:5000/v1/api/iserver/auth/login \
            -H 'Content-Type: application/json' \
            -d "{\"user\":\"${{ secrets.USER }}\",\"password\":\"${{ secrets.PASS }}\"}" \
            -o login.json

      - name: Fetch Account Data
        run: |
          curl -k -s -b cookies.txt https://localhost:5000/v1/api/iserver/account \
            -o account.json

      - name: Retrieve Cash Balance and print to log
        run: |
          # accountId auslesen
          ACCOUNT_ID=$(jq -r '.[0].accountId' account.json)
          echo "Account ID: $ACCOUNT_ID"

          # Ledger holen und Cash-Balance extrahieren
          BALANCE=$(curl -k -s -b cookies.txt \
            https://localhost:5000/v1/api/portfolio/$ACCOUNT_ID/ledger \
            | jq '.USD.cashbalance')

          # Ausgabe in die Logs
          echo "Cash Balance (USD): $BALANCE"