name: IBKR Cash Balance

on:
  workflow_dispatch:

jobs:
  print-balance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Start Gateway
        run: |
          # Container mit Client Portal API starten
          docker run -d --name ibkr -p 5000:5000 dradrian/ibportal:latest
          sleep 30  # kurz warten, bis das Gateway bereit ist

      - name: Login
        run: |
          # User/Pass an Gateway senden, Cookies speichern
          curl -k -s -c cookies.txt \
            -X POST https://localhost:5000/v1/api/iserver/auth/login \
            -H 'Content-Type: application/json' \
            -d "{\"user\":\"${{ secrets.USER }}\",\"password\":\"${{ secrets.PASS }}\"}"

      - name: Print Cash Balance
        run: |
          # accountId aus dem Account-Endpoint holen
          ACCOUNT_ID=$(curl -k -s -b cookies.txt https://localhost:5000/v1/api/iserver/account \
            | jq -r '.[0].accountId')
          # Ledger abrufen und USD-Cash-Balance ausgeben
          curl -k -s -b cookies.txt \
            https://localhost:5000/v1/api/portfolio/$ACCOUNT_ID/ledger \
            | jq '.USD.cashbalance | "Cash Balance (USD): \(. )"'