name: IBKR CP API Balance Check

on:
  workflow_dispatch:

jobs:
  get-account-balance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Download Client Portal Gateway
        run: |
          wget https://download2.interactivebrokers.com/portal/clientportal.gw.zip
          unzip clientportal.gw.zip -d clientportal.gw

      - name: Start Client Portal Gateway
        run: |
          chmod +x clientportal.gw/bin/run.sh
          nohup clientportal.gw/bin/run.sh root/conf.yaml > gateway.log 2>&1 &
          # Warten bis der Gateway-Service startet
          timeout 60 bash -c "until curl -k https://localhost:5000/v1/portal/oauth/status; do sleep 1; done"

      - name: Refresh OAuth2 Access Token
        id: auth
        env:
          CLIENT_ID: ${{ secrets.IBKR_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.IBKR_CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.IBKR_REFRESH_TOKEN }}
        run: |
          response=$(curl -s -k -X POST https://localhost:5000/v1/portal/oauth/token \
            -u "$CLIENT_ID:$CLIENT_SECRET" \
            -d grant_type=refresh_token \
            -d refresh_token="$REFRESH_TOKEN")
          echo "ACCESS_TOKEN=$(echo "$response" | jq -r .access_token)" >> $GITHUB_ENV

      - name: Get Account ID
        id: accounts
        run: |
          accounts=$(curl -s -k -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
            https://localhost:5000/v1/api/portfolio/accounts)
          echo "ACCOUNTS=$accounts" >> $GITHUB_ENV
          echo "ACCOUNT_ID=$(echo "$accounts" | jq -r '.[0].accountId')" >> $GITHUB_ENV

      - name: Get Account Summary
        run: |
          curl -k -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
            https://localhost:5000/v1/api/portfolio/${{ env.ACCOUNT_ID }}/summary | jq