name: IBKR Paper Trading Cash Balance

on:
  workflow_dispatch:

jobs:
  print-paper-balance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Start Gateway
        run: |
          # Container mit Client Portal API starten
          docker run -d --name ibkr-gateway -p 5000:5000 dradrian/ibportal:latest
          sleep 30  # warte bis das Gateway bereit ist

      - name: Login (Brokerage-Session)
        run: |
          # POST /iserver/auth/login
          curl -k -s -c cookies.txt -X POST \
            https://localhost:5000/v1/api/iserver/auth/login \
            -H 'Content-Type: application/json' \
            -d "{\"user\":\"${{ secrets.USER }}\",\"password\":\"${{ secrets.PASS }}\"}"

      - name: Check auth status
        run: |
          # GET /iserver/auth/status
          echo "Auth-Status:"
          curl -k -s -b cookies.txt \
            https://localhost:5000/v1/api/iserver/auth/status | jq .

      - name: Print Paper Trading Cash Balance
        run: |
          # 1) Account-Liste abrufen (GET /iserver/account)
          ACCOUNT_ID=$(curl -k -s -b cookies.txt \
            https://localhost:5000/v1/api/iserver/account \
            | jq -r '.[] | select(.accountDesc|test("paper";"i")) | .accountId')
          echo "Paper Trading Account ID: $ACCOUNT_ID"

          # 2) Ledger abrufen und USD.cashbalance ausgeben (GET /portfolio/{id}/ledger)
          curl -k -s -b cookies.txt \
            https://localhost:5000/v1/api/portfolio/$ACCOUNT_ID/ledger \
          | jq -r '.USD.cashbalance | "Paper Trading Cash Balance (USD): \(. )"'