name: IBKR Client Portal API Access

on:
  workflow_dispatch:

jobs:
  fetch-account:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Client Portal Gateway starten
        run: |
          docker run -d --name ibkr-gateway -p 5000:5000 dradrian/ibportal:latest
          echo "Warte 30s, bis das Gateway hochgefahren ist..."
          sleep 30

      - name: Login am Gateway
        run: |
          echo "Authentifiziere mit IBKR..."
          curl -k -s -c cookies.txt -X POST https://localhost:5000/v1/api/iserver/auth/login \
            -H 'Content-Type: application/json' \
            -d "{\"user\":\"${{ secrets.USER }}\",\"password\":\"${{ secrets.PASS }}\"}" \
            -o login.json

      - name: Debug: Login-Antwort & Cookies
        run: |
          echo "== Inhalt login.json =="
          if [ -s login.json ]; then
            cat login.json
          else
            echo "⚠️ login.json ist leer oder fehlt!"
          fi

          echo
          echo "== Dateiliste im Arbeitsverzeichnis =="
          ls -la .

          echo
          echo "== Cookies in cookies.txt =="
          if [ -s cookies.txt ]; then
            cat cookies.txt
          else
            echo "⚠️ cookies.txt ist leer oder fehlt!"
          fi

      - name: Debug: Auth-Status prüfen
        run: |
          echo "== Auth-Status vom Gateway =="
          curl -k -s -b cookies.txt https://localhost:5000/v1/api/iserver/auth/status | jq .

      - name: Debug: Container-Logs
        run: |
          echo "== IBKR-Gateway Logs =="
          docker logs ibkr-gateway || echo "Container existiert nicht oder ist gestoppt!"

      - name: Konto-Informationen abfragen
        run: |
          echo "Hole Kontodaten..."
          curl -k -s -b cookies.txt https://localhost:5000/v1/api/iserver/account -o account.json
          echo "Ergebnis:"
          cat account.json

      # Optional: als Artifact speichern
      #- name: Kontodaten als Artifact hochladen
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: ibkr-account-data
      #    path: account.json