# .github/workflows/sp500_automation.yml
name: sp500_automation

on:
  schedule:
    - cron: '12 12 * * 1-5'
  workflow_dispatch:

jobs:
  build-and-trade:
    runs-on: ubuntu-latest

    services:
      ibgateway:
        # statt ":stable" → ":latest" oder z.B. ":10.36.1c"
        image: ghcr.io/gnzsnz/ib-gateway:latest
        # explizit für den x86_64-Runner
        platform: linux/amd64
        env:
          TWS_USERID: ${{ secrets.IBKR_USER }}
          TWS_PASSWORD: ${{ secrets.IBKR_PASS }}
          TRADING_MODE: paper
        ports:
          - 4001:4001  # TWS-API
          - 5000:5000  # Client Portal Web API
        options: >-
          --health-cmd="nc -z localhost 4001"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=12

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq netcat-openbsd
          pip install pandas requests ib_insync ibind

      - name: Wait for IB Gateway API
        run: |
          echo "Warte auf IB Gateway API auf localhost:4001..."
          for i in {1..12}; do
            if nc -z localhost 4001; then
              echo "✅ IB Gateway API ist erreichbar."
              exit 0
            fi
            sleep 5
            echo "Noch nicht da, Versuch $i/12..."
          done
          echo "❌ IB Gateway API konnte nicht erreicht werden." >&2
          exit 1

      # … Rest der Steps bleibt unverändert …
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: pav-logs
          path: |
            sp500_pipeline.log
            sp500_agent.log