name: IBKR Paper Trading Cash Balance

on:
  workflow_dispatch:

jobs:
  print-paper-balance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Start Gateway
        run: |
          # Gateway-Container starten
          docker run -d --name ibkr-gateway -p 5000:5000 dradrian/ibportal:latest
          sleep 30  # warten bis der Service bereit ist

      - name: Validate SSO session
        run: |
          # GET /portal/sso/validate (SSO-Session muss gültig sein)
          STATUS=$(curl -k -s -o /dev/null -w '%{http_code}' \
            https://localhost:5000/v1/portal/sso/validate)
          if [ "$STATUS" -ne 200 ]; then
            echo "SSO validation failed with HTTP $STATUS"
            exit 1
          fi

      - name: Login (Brokerage-Session)
        run: |
          # POST /iserver/auth/login
          curl -k -s -c cookies.txt -X POST \
            https://localhost:5000/v1/api/iserver/auth/login \
            -H 'Content-Type: application/json' \
            -d "{\"user\":\"${{ secrets.USER }}\",\"password\":\"${{ secrets.PASS }}\"}"

      - name: Check auth status
        run: |
          # GET /iserver/auth/status
          curl -k -s -b cookies.txt \
            https://localhost:5000/v1/api/iserver/auth/status | jq .

      - name: Print Paper Trading Cash Balance
        run: |
          # GET /iserver/account → accountId für Paper Trading extrahieren
          ACCOUNT_ID=$(curl -k -s -b cookies.txt \
            https://localhost:5000/v1/api/iserver/account \
            | jq -r '.[] | select(.accountDesc | test("paper";"i")) | .accountId')
          echo "Account ID: $ACCOUNT_ID"

          # GET /portfolio/{accountId}/ledger → USD.cashbalance ausgeben
          curl -k -s -b cookies.txt \
            https://localhost:5000/v1/api/portfolio/$ACCOUNT_ID/ledger \
          | jq -r '.USD.cashbalance | "Paper Trading Cash Balance (USD): \(. )"'