name: Print IBKR Cash Balance

on:
  workflow_dispatch:

jobs:
  print-balance:
    runs-on: ubuntu-latest
    steps:
      - name: Start Client Portal Gateway
        run: |
          # Gateway in Docker starten (Port 5000)
          docker run -d --name ibkr-gateway -p 5000:5000 dradrian/ibportal:latest
          sleep 30  # kurz warten, bis das Gateway bereit ist

      - name: Login
        run: |
          # Brokerage-Session starten (POST /iserver/auth/login)
          curl -k -s -c cookies.txt -X POST https://localhost:5000/v1/api/iserver/auth/login \
            -H 'Content-Type: application/json' \
            -d "{\"user\":\"${{ secrets.USER }}\",\"password\":\"${{ secrets.PASS }}\"}"

      - name: Print Cash Balance
        run: |
          # 1) accountId holen (GET /iserver/account)
          ACCOUNT_ID=$(curl -k -s -b cookies.txt https://localhost:5000/v1/api/iserver/account \
            | jq -r '.[0].accountId')

          # 2) Ledger abrufen und USD-Cash-Balance drucken (GET /portfolio/{accountId}/ledger)
          curl -k -s -b cookies.txt \
            https://localhost:5000/v1/api/portfolio/$ACCOUNT_ID/ledger \
          | jq '.USD.cashbalance | "Cash Balance (USD): \(. )"'